- name: git module demo

  groups:
    - all

  # sudo: root

  tasks:

    - !facts

    #- !directory
    #  path: /opt/jeti
    #  remove: true
    #  recurse: true
    
    #- !directory
    #  path: /opt/func2
    #  remove: true
    #  recurse: true

    - !dnf
      package: git
      beforetask:
          condition: (eq jet_os_flavor "Fedora")

    - !apt
      package: git
      beforetask:
          condition: (eq jet_os_flavor "Debian")

    - !pacman
      package: git
      beforetask:
        condition: (eq jet_os_flavor "Arch")
    
    - !zypper
      package: git
      beforetask:
        condition: (eq jet_os_flavor "Suse")
    
    - !git
      repo: https://github.com/jetporch/jetporch.git
      path: /opt/jetporch1
      branch: main

    # SSH-clone example
    # change the following to some private repo
    # you have access to and
    # invoke CLI with --forward-agent

    # - !git
    #  repo: git@github.com:mpdehaan/func.git
    #  path: /opt/func2
    #  branch: master


