- name: shell tricks
  groups: 
    - all

  tasks:

  - !shell
    cmd: echo hi

  - !fail
    name: this will not fail
    aftertask:
        ignore_errors: true

  - !fail
    name: this will fail




