- name: this is a demo of items loops
  groups: 
   - all

  defaults:

     a_list:
       - uno
       - dos
       - tres
     b_list:
       - { a: "one", b: 1 }
       - { a: "two", b: 2 }
  
     narf: "Narf!"
     fjord: "Fjord!!!"

  tasks:

   - !echo
     name: "looping over a basic list: uno, dos, tres!"
     msg: "{{ item }}"
     beforetask:
        items: a_list

   - !echo
     name: "looping over a structured list"
     msg: "a={{ item.a }} b={{ item.b}}"
     beforetask:
         items: b_list   

   - !echo
     name: "this time the list is not from a variable"
     msg: "{{ item }}"
     beforetask:
        items:
           - "{{ narf }}"
           - asdf
           - jkl
   
   - !echo
     name: "this time with a list of dicts"
     msg: "{{ item.a }}, {{ item.b }}"
     beforetask:
        items:
           - { a: "a", b: "b" }
           - { a: "c", b: "d" }



          

